# https://docs.travis-ci.com/user/languages/android/

language: android
jdk: oraclejdk8
sudo: required

env:
  global:
    - API_LEVEL=25
    - EMUL_LEVEL=21
    - BUILD_TOOL=25.0.0
    - ABI=armeabi-v7a
    - TAG=google_apis

android:
  components:
    - tools
    - platform-tools
    - build-tools-$BUILD_TOOL
    - android-$API_LEVEL
    - andorid-$EMUL_LEVEL
    - addon-google_apis-google-$API_LEVEL
    - addon-google_apis-google-$EMUL_LEVEL
    - extra-google-google_play_services
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository
#    - sys-img-$ABI-android-$API_LEVEL
    - sys-img-armeabi-v7a-google_apis-$API_LEVEL
    - sys-img-armeabi-v7a-google_apis-$EMUL_LEVEL

before_script:
  - echo no | android create avd --force -n test -t "android-"$EMUL_LEVEL --abi $ABI --tag $TAG
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator

script:
  - ./gradlew clean check connectedCheck 
